AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless PR Police
Resources:
  Issuer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 300
      MemorySize: 64
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /issues
            Method: post
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SLACK_TOKEN
          NODE_ENV: !Ref NODE_ENV
          GITHUB_TOKEN: !Ref GITHUB_TOKEN

Parameters:
  SLACK_TOKEN:
    Type: String
    Description: Slack bot user token to send a message
    NoEcho: true
  NODE_ENV:
    Default: test
    Type: String
    Description: Environment of performing Lambda
    NoEcho: true
  GITHUB_TOKEN:
    Type: String
    Description: Token of GitHub Apps
    NoEcho: true
