AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless PR Police
Resources:
  GetPRInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: index.createIssue
      Runtime: nodejs8.10
      Timeout: 300
      MemorySize: 64
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /create_issue
            Method: post
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          NODE_ENV: !Ref NodeEnv
          GitHubToken: !Ref GitHubToken

Parameters:
  SlackToken:
    Type: String
    Description: Slack bot user token to send a message
    NoEcho: true
  NodeEnv:
    Default: test
    Type: String
    Description: Environment of performing Lambda
    NoEcho: true
  GitHubToken:
    Type: String
    Description: Token of GitHub Apps
    NoEcho: true
